# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = traps.out
SRCS = main.cpp ClapTrap.cpp ScavTrap.cpp

include ../template.mk

ClapTrap.cpp: ClapTrap.hpp
main.cpp ScavTrap.cpp: ScavTrap.hpp
