# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = traps.out
SRCS = main.cpp ClapTrap.cpp

include ../template.mk

main.cpp ClapTrap.cpp: ClapTrap.hpp
